/*
 * Interrupt_Enum.h
 *
 *  Created on: 11 mar. 2021
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_CORE_INTERRUPT_XHEADER_INTERRUPT_ENUM_H_
#define XDRIVER_MCU_CORE_INTERRUPT_XHEADER_INTERRUPT_ENUM_H_

typedef enum
{
    CORE_enINTERRUPT_VECTOR_MASK_INT1 = 0x0001U,
    CORE_enINTERRUPT_VECTOR_MASK_INT2 = 0x0002U,
    CORE_enINTERRUPT_VECTOR_MASK_INT3 = 0x0004U,
    CORE_enINTERRUPT_VECTOR_MASK_INT4 = 0x0008U,
    CORE_enINTERRUPT_VECTOR_MASK_INT5 = 0x0010U,
    CORE_enINTERRUPT_VECTOR_MASK_INT6 = 0x0020U,
    CORE_enINTERRUPT_VECTOR_MASK_INT7 = 0x0040U,
    CORE_enINTERRUPT_VECTOR_MASK_INT8 = 0x0080U,
    CORE_enINTERRUPT_VECTOR_MASK_INT9 = 0x0100U,
    CORE_enINTERRUPT_VECTOR_MASK_INT10 = 0x0200U,
    CORE_enINTERRUPT_VECTOR_MASK_INT11 = 0x0400U,
    CORE_enINTERRUPT_VECTOR_MASK_INT12 = 0x0800U,
    CORE_enINTERRUPT_VECTOR_MASK_INT13 = 0x1000U,
    CORE_enINTERRUPT_VECTOR_MASK_INT14 = 0x2000U,
    CORE_enINTERRUPT_VECTOR_MASK_DLOGINT = 0x4000U,
    CORE_enINTERRUPT_VECTOR_MASK_RTOSINT = 0x8000U,
    CORE_enINTERRUPT_VECTOR_MASK_NMI = 0x8001U,
    CORE_enINTERRUPT_VECTOR_MASK_EMUINT = 0x8002U,
    CORE_enINTERRUPT_VECTOR_MASK_UNDEF = 0xFFFFU
}CORE_nINTERRUPT_VECTOR_MASK;

typedef enum
{
    CORE_enINTERRUPT_VECTOR_RESET = 0U,
    CORE_enINTERRUPT_VECTOR_INT1 = 1U,
    CORE_enINTERRUPT_VECTOR_INT2 = 2U,
    CORE_enINTERRUPT_VECTOR_INT3 = 3U,
    CORE_enINTERRUPT_VECTOR_INT4 = 4U,
    CORE_enINTERRUPT_VECTOR_INT5 = 5U,
    CORE_enINTERRUPT_VECTOR_INT6 = 6U,
    CORE_enINTERRUPT_VECTOR_INT7 = 7U,
    CORE_enINTERRUPT_VECTOR_INT8 = 8U,
    CORE_enINTERRUPT_VECTOR_INT9 = 9U,
    CORE_enINTERRUPT_VECTOR_INT10 = 10U,
    CORE_enINTERRUPT_VECTOR_INT11 = 11U,
    CORE_enINTERRUPT_VECTOR_INT12 = 12U,
    CORE_enINTERRUPT_VECTOR_INT13 = 13U,
    CORE_enINTERRUPT_VECTOR_INT14 = 14U,
    CORE_enINTERRUPT_VECTOR_DLOGINT = 15U,
    CORE_enINTERRUPT_VECTOR_RTOSINT = 16U,
    CORE_enINTERRUPT_VECTOR_RESERVED = 17U,
    CORE_enINTERRUPT_VECTOR_NMI = 18U,
    CORE_enINTERRUPT_VECTOR_EMUINT = 19U,
    CORE_enINTERRUPT_VECTOR_USER1 = 20U,
    CORE_enINTERRUPT_VECTOR_USER2 = 21U,
    CORE_enINTERRUPT_VECTOR_USER3 = 22U,
    CORE_enINTERRUPT_VECTOR_USER4 = 23U,
    CORE_enINTERRUPT_VECTOR_USER5 = 24U,
    CORE_enINTERRUPT_VECTOR_USER6 = 25U,
    CORE_enINTERRUPT_VECTOR_USER7 = 26U,
    CORE_enINTERRUPT_VECTOR_USER8 = 27U,
    CORE_enINTERRUPT_VECTOR_USER9 = 28U,
    CORE_enINTERRUPT_VECTOR_USER10 = 29U,
    CORE_enINTERRUPT_VECTOR_USER11 = 30U,
    CORE_enINTERRUPT_VECTOR_USER12 = 31U,
    CORE_enINTERRUPT_VECTOR_UNDEF = 0xFFFFU
}CORE_nINTERRUPT_VECTOR;


typedef enum
{
    CORE_enINTERRUPT_STATUS_CLEAR = 0x0000U,
    CORE_enINTERRUPT_STATUS_PEND = 0x0001U,
    CORE_enINTERRUPT_STATUS_UNDEF = 0xFFFFU
}CORE_nINTERRUPT_STATUS;


#endif /* XDRIVER_MCU_CORE_INTERRUPT_XHEADER_INTERRUPT_ENUM_H_ */
